name: Complete Infrastructure

env:
  TERRAFORM_VERSION: 1.5.7
  ALB_NAME: ${{ vars.ALB_NAME }}
  FUNCTION_NAME: ${{ vars.FUNCTION_NAME }}

on:
#   push:
#     # branches: [ develop ]
#     # paths:
#     #   - modules/api_gateway/**
#     #   - prd.tfvars
#     #   - .github/workflows/infra-complete.yml
#     #   - locals.tf
#     #   - main.tf
#     #   - outputs.tf
#     #   - providers.tf
#     #   - variables.tf

#   repository_dispatch:
#     types: [infra-iac-completed]
  workflow_dispatch:

  # workflow_call:
jobs:
  complete-infra:
    name: Complete Infrastructure Setup
    runs-on: codebuild-github-lncr-iac-${{ github.run_id }}-${{ github.run_attempt }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region us-east-1 --name lncr-prd-eks

    - name: Get ALB Listener ARN from EKS
      run: |
        # Use diretamente o ARN conhecido do ALB
        ALB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?LoadBalancerName=='$ALB_NAME'].LoadBalancerArn" --output text)
        echo "ALB_ARN found: $ALB_ARN"

        ALB_LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn $ALB_ARN --query "Listeners[0].ListenerArn" --output text)
        echo "ALB_LISTENER_ARN found: $ALB_LISTENER_ARN"
        
        if [ -z "$ALB_LISTENER_ARN" ]; then
          echo "Error: ALB Listener ARN not found"
          exit 1
        fi
        echo "ALB_LISTENER_ARN=$ALB_LISTENER_ARN" >> $GITHUB_ENV

    - name: Get Function ARN
      run: |
        
        FUNCTION_ARN=$(aws lambda get-function --function-name "$FUNCTION_NAME" --query 'Configuration.FunctionArn' --output text 2>&1)
        echo "FUNCTION_ARN found: $FUNCTION_ARN"
        if [ -z "$FUNCTION_ARN" ]; then
          echo "Error: Function ARN not found"
          exit 1ep
        fi
        echo "FUNCTION_ARN=$FUNCTION_ARN" >> $GITHUB_ENV

    - name: Deploy API Gateway Configuration with ALB
      env:
        TF_VAR_eks_dns_nlb: ${{ env.ALB_LISTENER_ARN }}
      run: |
        terraform init
        terraform apply \
          -target=module.api_gateway \
          -var="eks_nlb_listener_arn=${{ env.ALB_LISTENER_ARN }}" \
          -var="lambda_function_arn=${{ env.FUNCTION_ARN }}" \
          -var-file="prd.tfvars" \
          -auto-approve