name: Complete Infrastructure

env:
  TERRAFORM_VERSION: 1.5.7

on:
  push:
    branches: [ develop ]
    paths:
      - modules/api_gateway/**
      - prd.tfvars
      - .github/workflows/infra-complete.yml
      - locals.tf
      - main.tf
      - outputs.tf
      - providers.tf
      - variables.tf

  repository_dispatch:
    types: [infra-iac-completed]
  workflow_dispatch:

  workflow_call:

jobs:
  complete-infra:
    name: Complete Infrastructure Setup
    runs-on: codebuild-github-lncr-iac-${{ github.run_id }}-${{ github.run_attempt }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region us-east-1 --name lncr-prd-eks

    

    - name: Get NLB Listener ARN from EKS
      run: |
        # Use diretamente o ARN conhecido do NLB
        NLB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[].LoadBalancerArn" --output text | grep lncr | head -1)
        echo "NLB_ARN found: $NLB_ARN"

        NLB_LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn $NLB_ARN --query "Listeners[0].ListenerArn" --output text)
        echo "NLB_LISTENER_ARN found: $NLB_LISTENER_ARN"
        
        if [ -z "$NLB_LISTENER_ARN" ]; then
          echo "Error: NLB Listener ARN not found"
          exit 1
        fi
        echo "NLB_LISTENER_ARN=$NLB_LISTENER_ARN" >> $GITHUB_ENV

    - name: Get Function ARN
      run: |
        
        FUNCTION_ARN=$(aws lambda get-function --function-name lncr-prd-custom-authorizer --query 'Configuration.FunctionArn' --output text)
        echo "FUNCTION_ARN found: $FUNCTION_ARN"
        if [ -z "$FUNCTION_ARN" ]; then
          echo "Error: Function ARN not found"
          exit 1
        fi
        echo "FUNCTION_ARN=$FUNCTION_ARN" >> $GITHUB_ENV

    - name: Deploy API Gateway Configuration with NLB
      env:
        TF_VAR_eks_dns_nlb: ${{ env.NLB_LISTENER_ARN }}
      run: |
        terraform init
        terraform apply \
          -target=module.api_gateway \
          -var="eks_nlb_listener_arn=${{ env.NLB_LISTENER_ARN }}" \
          -var="lambda_function_arn=${{ env.FUNCTION_ARN }}" \
          -var-file="prd.tfvars" \
          -auto-approve